spring.application.name=tinder-ai-backend
spring.ai.ollama.chat.options.model=llama3
#spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}

startup-actions.initialiseProfiles=true
tinderAi.LookingForGender=woman